### ISSUE TITLE
Pip installation error.

### ISSUE THREAD

**Issue by meyverick** [ChristophSchranz/Tweaker-3#26]
Python 3.10.6
Pip 22.2.2

`C:\Windows\System32>pip install git+https://github.com/ChristophSchranz/Tweaker-3.git
Collecting git+https://github.com/ChristophSchranz/Tweaker-3.git
  Cloning https://github.com/ChristophSchranz/Tweaker-3.git to c:\users\meyverick\appdata\local\temp\pip-req-build-v3a_o4vf
  Running command git clone --filter=blob:none --quiet https://github.com/ChristophSchranz/Tweaker-3.git 'C:\Users\Meyverick\AppData\Local\Temp\pip-req-build-v3a_o4vf'
  Resolved https://github.com/ChristophSchranz/Tweaker-3.git to commit f9db764bf7c68100c632d64c396491044b0ea0f4
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      running egg_info
      creating tweaker3.egg-info
      writing tweaker3.egg-info\PKG-INFO
      writing dependency_links to tweaker3.egg-info\dependency_links.txt
      writing entry points to tweaker3.egg-info\entry_points.txt
      writing requirements to tweaker3.egg-info\requires.txt
      writing top-level names to tweaker3.egg-info\top_level.txt
      writing manifest file 'tweaker3.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "C:\Users\Meyverick\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\Meyverick\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Meyverick\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 308, in run
          self.find_sources()
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 316, in find_sources
          mm.run()
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 560, in run
          self.add_defaults()
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 597, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\command\sdist.py", line 106, in add_defaults
          super().add_defaults()
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 250, in add_defaults
          self._add_defaults_python()
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\command\sdist.py", line 117, in _add_defaults_python
          build_py = self.get_finalized_command('build_py')
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 306, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 109, in ensure_finalized
          self.finalize_options()
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\command\build_py.py", line 37, in finalize_options
          orig.build_py.finalize_options(self)
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\_distutils\command\build_py.py", line 59, in finalize_options
          self.package_dir[name] = convert_path(path)
        File "C:\Users\Meyverick\AppData\Local\Temp\pip-build-env-rv6wsqfl\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 139, in convert_path
          raise ValueError("path '%s' cannot end with '/'" % pathname)
      ValueError: path './' cannot end with '/'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by ChristophSchranz** [comment]
Hi,
it seems like there is a problem with the slash for paths under windows.
See here: https://stackoverflow.com/questions/20356482/valueerror-path-conf-cannot-end-with

**Comment by ChristophSchranz** [comment]
Please try again and reopen if it still doesn't work.
